-- Seed members for Supabase
-- Run in the Supabase SQL editor or via psql
-- Uses INSERT ... ON CONFLICT (name) DO UPDATE to upsert by name.
-- If you don't have a unique constraint on name, change to ON CONFLICT DO NOTHING
-- or just use plain INSERT.

INSERT INTO members (id, name, "Rank", "THP", "S1_Power", "S1_Type", "S2_Power", "S2_Type", "Strike_Team", "Availability", created_at, updated_at)
VALUES
  (gen_random_uuid(), 'Ruthless cajun',       'R4', 146.6,  45800000, 'Air',  38500000, 'Tank', false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'Gigiyy',               'R3', 147.4,  44400000, 'Tank', NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'BaconALcH3MiST',       'R4', 122.9,  40800000, 'Air',  NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'SammiX 삼미',           'R3', 107.8,  37000000, NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'deezzz420',             'R4', 107.4,  36100000, 'Air',  NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'Dhilldo',               'R4', 116.7,  35400000, NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'Be BetteR',             'R3', 101.2,  35300000, 'Tank', NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'Jacksonrebel',          'R3',  94.3,  32900000, NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), '50 Cal Diplomacy',      'R3', 100.0,  32500000, NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'ELLIOT5',               'R4',  93.2,  31900000, NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'PAINisthebestTeacher',  'R5',  83.9,  31910000, 'Tank', 24910000, 'Air',  false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'ShadowMohawk',          'R4',  85.4,  31700000, 'Tank', 25500000, 'Air',  false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'Saucy808',              'R4',  86.6,  31400000, 'Tank', 26300000, 'Air',  false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'Guilherra',             'R3',  90.2,  31300000, NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'CockaMaemie',           'R3',  79.5,  31200000, NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'Paxaz',                 'R3',  84.0,  31000000, NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'skibidi rizz toilet5',  'R4',  83.6,  30800000, 'Tank', NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'GHOST BR',              'R3',  82.7,  30700000, NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'KABRAL9',               'R3',  85.2,  30700000, NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'MavKel',                'R3',  90.1,  30500000, NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'WapitiDreaming',        'R4',  85.5,  30400000, 'Tank', 24300000, 'Air',  false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'Shadows1983',           'R3',  86.0,  30400000, NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'lunacyde',              'R3',  94.1,  30200000, NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'Andressita31',          'R3',  79.9,  30100000, NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'JoSto03',               'R3',  84.5,  29900000, NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'GatitoTriste',          'R4',  78.2,  29600000, 'Tank', NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'Thiagoksp',             'R3',  84.0,  29500000, NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'stonerD',               'R3',  79.1,  29400000, NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'Abycon',                'R3',  75.7,  29300000, NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'Captain Phoenix',       'R2',  87.5,  29300000, 'Tank', NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'DestructorDeSnacks',    'R3',  87.0,  29200000, NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'GenioFonseca',          'R3',  78.8,  29200000, NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'Echo Magistrada',       'R3',  81.2,  29100000, NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'Alfredm87',             'R3',  91.2,  28300000, NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'Fancyfootwork',         'R3',  83.1,  27200000, NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'Argus III',             'R3',  82.9,  27000000, NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'BeastMachine',          'R3',  83.4,  26900000, NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'JU STARS',              'R3',  24.0,  NULL,     NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  -- Members with no squad data (THP = 0)
  (gen_random_uuid(), 'Acid Hologram',         'R3',   0.0,  NULL,     NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'Amélie POulain',        'R3',   0.0,  NULL,     NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'DazMiq',                'R3',   0.0,  NULL,     NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'Dioguines',             'R3',   0.0,  NULL,     NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'Dredd Pirate Roberts',  'R3',   0.0,  NULL,     NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'DRMAlito',              'R3',   0.0,  NULL,     NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'Duval and Co',          'R3',   0.0,  NULL,     NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'Emma Ö',               'R3',   0.0,  NULL,     NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'Flores 19',             'R3',   0.0,  NULL,     NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'GoyeliCR',              'R3',   0.0,  NULL,     NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'Jboo1027',              'R3',   0.0,  NULL,     NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'jcruzrico',             'R3',   0.0,  NULL,     NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'Kimy Q',               'R3',   0.0,  NULL,     NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'km1180',                'R3',   0.0,  NULL,     NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'kokis Titito',          'R3',   0.0,  NULL,     NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'Laprada',               'R3',   0.0,  NULL,     NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'Liveone',               'R3',   0.0,  NULL,     NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'LuffyJr',               'R3',   0.0,  NULL,     NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'LuffyRdz',              'R3',   0.0,  NULL,     NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'Luis René',            'R3',   0.0,  NULL,     NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'Luisbolter',            'R3',   0.0,  NULL,     NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'Mestre yoda',           'R3',   0.0,  NULL,     NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'millmj08',              'R3',   0.0,  NULL,     NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'MõistMeatSocket',      'R3',   0.0,  NULL,     NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'MONKY LUFFY',           'R3',   0.0,  NULL,     NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'My name JeFF',          'R3',   0.0,  NULL,     NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'nicki',                 'R3',   0.0,  NULL,     NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'Papa Penu',             'R3',   0.0,  NULL,     NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'PenséQueEraFacil',     'R3',   0.0,  NULL,     NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'pol0loco',              'R3',   0.0,  NULL,     NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'ponygirlrocks11',       'R3',   0.0,  NULL,     NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'RepoMan6060',           'R3',   0.0,  NULL,     NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'SGT SMOKER',            'R3',   0.0,  NULL,     NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'Simplemente Val',       'R3',   0.0,  NULL,     NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'SimplySmk',             'R3',   0.0,  NULL,     NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'SirFred1',              'R3',   0.0,  NULL,     NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'TainaraPompeu',         'R3',   0.0,  NULL,     NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'Taiska Valk',           'R3',   0.0,  NULL,     NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'Thomas Callahan III',   'R3',   0.0,  NULL,     NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'Vikernes 666',          'R3',   0.0,  NULL,     NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'XMEIGA',                'R3',   0.0,  NULL,     NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'XxX Bradley XxX',       'R3',   0.0,  NULL,     NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'XxX Sparky XxX',        'R3',   0.0,  NULL,     NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  -- R2 members
  (gen_random_uuid(), 'AustinPOwers',          'R2',   0.0,  NULL,     NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'ChessM',                'R2',   0.0,  NULL,     NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'Comandante Pico',       'R2',   0.0,  NULL,     NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'Craig D03',             'R2',   0.0,  NULL,     NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'Jon McCall22',          'R2',   0.0,  NULL,     NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'Leonnoo',               'R2',   0.0,  NULL,     NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'Martin 2525',           'R2',   0.0,  NULL,     NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'Michdab',               'R2',   0.0,  NULL,     NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'Slapya',                'R2',   0.0,  NULL,     NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  -- R1 members
  (gen_random_uuid(), '11daniella',            'R1',   0.0,  NULL,     NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), '4dr13L',                'R1',   0.0,  NULL,     NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'DAN140296',             'R1',   0.0,  NULL,     NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'Grand Emperor Viejo',   'R1',   0.0,  NULL,     NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'King Arthur 500',       'R1',   0.0,  NULL,     NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'Luffycita',             'R1',   0.0,  NULL,     NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'MINI ME',               'R1',   0.0,  NULL,     NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'Mushroom Helmet',       'R1',   0.0,  NULL,     NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'Reiley',                'R1',   0.0,  NULL,     NULL,   NULL,     NULL,   false, NULL, NOW(), NOW()),
  (gen_random_uuid(), 'Roeezz',                'R1',   0.0,  NULL,     NULL,   NULL,     NULL,   false, NULL, NOW(), NOW())
ON CONFLICT (name) DO UPDATE SET
  "Rank"        = EXCLUDED."Rank",
  "THP"         = EXCLUDED."THP",
  "S1_Power"    = EXCLUDED."S1_Power",
  "S1_Type"     = EXCLUDED."S1_Type",
  "S2_Power"    = EXCLUDED."S2_Power",
  "S2_Type"     = EXCLUDED."S2_Type",
  "Strike_Team" = EXCLUDED."Strike_Team",
  updated_at    = NOW();
